### ISSUE TITLE
[Command] Script Idea

### ISSUE THREAD

**Issue by talamortis** [azerothcore/mod-alpha-rewards#10]
Make a command script for this module so that 

- [x] Players can request to see how many points they have got
- [x] Admins can add GP to players or remove them
- [x] Admins and GM's can view how many game points a player has.

**Comment by ZeegCL** [comment]
`.gamepoint` => shows your game points
`.gamepoint add $name $amount` => adds points to a player 
`.gamepoint view $name` => views a player's game points

**Comment by talamortis** [comment]
Since we are using DataMap we will have to do a Update feature so it saves to the DB after x amount of minutes. This way if server does crash ect it will save the points on a interval and they will not be lost.

It will also make it easier for the creature to get the value then as we can use a DB query for this.

**Comment by talamortis** [comment]
https://github.com/azerothcore/mod-alpha-rewards/commit/6c4248d928c2ff66694cdee51ccd62cdf35ed9e8
