### ISSUE TITLE
Reward points for the first random dungeon (DF) in a day

### ISSUE THREAD

**Issue by ZeegCL** [azerothcore/mod-alpha-rewards#2]
Reward players X amount of points for the first completion of a random dungeon in Dungeon Finder. Take into consideration that the game already gives an extra daily reward.

**This could need a new hook in the core**

**Note:** X value should be in config

**Comment by talamortis** [comment]
This has been done by the complete on daily heroic quest
As seen here: https://github.com/azerothcore/mod-alpha-rewards/blob/master/src/mod-alpha-rewards-player.cpp#L41

At the moment I'm doing update to this to allow players to add or remove quests via DB
